In [1]:
import numpy as np
from os.path import join, isfile
from skimage.measure import regionprops_table
import pandas as pd
from inducedRainbow.clusterSize import inducedRainbowAnalysis
from inducedRainbow.clusterSize import markovianClusterSimulation
import os
from os import listdir
import random
import pandas as pd

In [2]:
df = pd.read_csv("/Volumes/Aortas/Aorta/results/inducedRainbow/allClusterSizesRed.csv")
savePath = "/Volumes/Aortas/Aorta/results/inducedRainbow/markovianCluster/infer0-10"

In [3]:
df0_5 = df.loc[df.age == "P0-5"]
df5_10 = df.loc[df.age == "P5-10"]
df0_10 = df.loc[df.age == "P0-5"]

In [4]:
df0_5

age    aorta    1    2   3   4   5  6  7  8  9  10  11  12  13  14  15
0  P0-5  aorta01  409   71  27  11   3  2  1  0  0   0   0   0   0   0   0
1  P0-5  aorta02  327   58  20   9   4  2  1  0  0   0   0   0   0   0   0
2  P0-5  aorta03  270   61  31  16   6  2  3  1  0   0   0   0   0   0   0
3  P0-5  aorta04  315  104  33  14  14  2  0  2  0   0   0   1   0   0   0
4  P0-5  aorta05  228   71  25   2   7  4  0  0  0   0   0   0   0   0   0
5  P0-5  aorta06  262   64  23  15   6  3  2  0  0   0   0   0   0   0   0

In [5]:
dic0_5 = inducedRainbowAnalysis.getClusterSizes(df0_5)
dic5_10 = inducedRainbowAnalysis.getClusterSizes(df5_10)
dic0_10 = inducedRainbowAnalysis.getClusterSizes(df0_10)

In [9]:
for key1 in dic0_5:
    for key2 in dic5_10:
        resultsRandomCluster = markovianClusterSimulation.markovianClusterInfer(dic0_5[key1], dic5_10[key2], 1000)
        resultsRandomDivision = markovianClusterSimulation.markovianDivisionInfer(dic0_5[key1], dic5_10[key2], 1000)

        filenameCluster = "markovianClusterSimulation_0-5_" + key1 + "_5-10_" +  key2 +  ".txt"
        filenameDivision = "markovianDivisionSimulation_0-5_" + key1 + "_5-10_" + key2 + ".txt"
        np.savetxt(join(savePath, filenameCluster), resultsRandomCluster)
        np.savetxt(join(savePath, filenameDivision), resultsRandomDivision)

In [28]:
resultsRandomCluster = markovianClusterInfer(dic0_5['aorta01'], dic5_10['aorta01'], 1000)

In [39]:
np.max(resultsRandomCluster)

12

In [35]:
resultsRandomDiv = markovianDivisionInfer(dic0_5['aorta01'], dic5_10['aorta01'], 1000)

In [38]:
np.max(resultsRandomDiv)

20

In [21]:
unique, counts = np.unique(resultsRandomCluster, return_counts=True)

In [22]:
counts

array([2, 2, 2, 3, 1, 1, 2, 2, 2, 3, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2,
       1, 1, 2, 3, 1, 2, 2, 1, 2, 1, 4, 1, 1, 1, 2, 1, 1, 3, 3, 1, 2, 1,
       2, 3, 2, 1, 2, 1, 1, 3, 2, 1, 1, 2, 1, 2, 3, 3, 3, 1, 3, 1, 1, 3,
       1, 2, 1, 3, 4, 4, 3, 2, 2, 2, 1, 3, 1, 1, 3, 2, 2, 2, 1, 1, 1, 2,
       1, 2, 1, 1, 1, 2, 3, 3, 2, 1, 1, 3, 3, 1, 2, 2, 3, 2, 2, 1, 2, 2,
       2, 3, 2, 1, 5, 1, 1, 2, 4, 1, 1, 1, 2, 2, 1, 1, 1, 3, 2, 1, 3, 2,
       1, 2, 2, 3, 1, 2, 1, 1, 1, 2, 3, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1,
       1, 1, 3, 1, 3, 3, 1, 4, 1, 4, 1, 3, 3, 2, 2, 2, 2, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 2, 3, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 5, 1, 3, 2,
       1, 1, 1, 2, 1, 3, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 3, 3, 2, 3, 2,
       2, 1, 2, 2, 3, 3, 1, 2, 3, 1, 2, 1, 1, 3, 3, 2, 1, 1, 3, 1, 2, 1,
       3, 2, 2, 2, 2, 1, 2, 1, 4, 1, 3, 2, 3, 3, 1, 3, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 3, 2, 3, 4, 7, 1, 4, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 4, 5,
       1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 3,

In [23]:
unique

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [ ]:
        clusterSizesRandomCluster = []
for i in range(1,markedClusters +1):
    clusterSizesRandomCluster.append(randomCluster.count(i))
resultsRandomCluster.append(clusterSizesRandomCluster)
return resultsRandomCluster

In [35]:
clusters = dic0_5['aorta01']

In [36]:
c = 1
for i in range(len(clusters)):
    if i == 0:
        cluster = np.full(clusters[i], c)
    else:
        cluster = np.concatenate([cluster, np.full(clusters[i], c)])
    c += 1

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3


In [41]:
clusters = dic5_10['aorta01']

In [42]:
divided = 0
for i in range(len(clusters)):
    divided += clusters[i] -1

In [43]:
divided

394

In [38]:
clusters

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [44]:
len(np.unique(cluster))

524

In [45]:
np.unique(cluster)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [46]:
import random

In [50]:
for i in range(1000):
    print(random.randrange(1, 3))

1
2
2
1
2
1
2
2
2
1
2
1
2
1
1
1
2
2
1
2
2
2
1
1
1
2
2
1
1
2
2
1
2
2
2
1
1
2
1
2
2
2
1
1
1
1
1
2
2
1
2
2
2
2
2
2
1
2
1
2
1
1
1
1
1
2
2
2
2
2
2
1
1
2
2
1
1
1
1
1
1
1
2
1
2
2
2
1
2
2
2
1
1
1
2
2
2
2
1
2
1
1
2
2
1
1
2
2
1
1
2
2
2
1
1
2
1
2
2
1
1
2
1
1
2
2
1
1
1
1
1
1
2
1
2
1
1
2
1
1
2
1
2
2
1
1
1
2
1
1
1
2
2
1
2
1
2
2
1
2
2
2
2
2
2
2
1
2
1
2
2
1
2
2
1
1
1
1
2
2
2
2
1
1
1
2
1
2
1
1
1
1
2
1
2
2
2
2
1
1
2
1
1
2
2
1
2
1
1
1
2
1
1
1
1
2
2
1
1
2
2
2
1
1
2
1
2
1
1
1
1
1
2
2
1
1
2
1
1
1
2
1
1
2
2
1
1
1
2
1
1
2
2
2
2
2
1
2
1
1
2
1
1
1
2
2
1
2
2
2
1
1
1
2
1
1
2
2
2
1
2
2
1
1
1
1
2
1
2
1
1
1
2
2
1
1
2
2
1
1
2
1
1
2
1
1
1
2
2
2
1
2
1
2
1
1
1
2
2
2
1
1
2
2
2
2
1
1
1
1
2
1
2
2
2
1
2
2
1
1
1
2
1
1
2
2
2
1
1
1
2
1
2
1
1
1
2
2
2
1
2
1
2
2
2
2
1
1
2
1
1
1
1
1
1
2
2
2
1
1
2
2
1
1
1
2
1
2
2
2
2
2
1
1
1
2
2
1
2
2
1
1
1
2
1
1
1
2
1
1
1
2
1
1
2
1
1
2
2
2
1
2
1
1
1
2
1
1
1
1
1
1
2
2
1
2
2
1
2
1
1
2
1
1
2
2
1
1
2
1
2
1
2
2
2
1
1
1
2
2
1
1
1
2
1
2
1
1
1
1
1
2
2
2
2
1
1
2
2
2
1
1
1
2
1
1
2
1
1
2
2
1
2
2
1
1
1
1
1
1
